In [1]:
import numpy as np 

liste =[1,2,3,4,5,6]

list = np.arange(100000)

list

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [2]:

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])