In [1]:
import numpy as np

In [2]:
list = np.random.randint(0,5,(4,4))

In [3]:
list

array([[0, 3, 1, 0],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])

In [4]:
list2 = list.view()

In [5]:
list2

array([[0, 3, 1, 0],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])

In [6]:
list2[0]= [9,9,9,9]
list2

array([[9, 9, 9, 9],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])

In [7]:
list

array([[9, 9, 9, 9],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])

In [8]:
list3 = list2.copy()
list3

array([[9, 9, 9, 9],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])

In [9]:
list3[1] = [4,45,68,7]

In [10]:
list3


array([[ 9,  9,  9,  9],
       [ 4, 45, 68,  7],
       [ 4,  4,  3,  0],
       [ 4,  4,  4,  2]])

In [11]:
list2

array([[9, 9, 9, 9],
       [4, 0, 2, 4],
       [4, 4, 3, 0],
       [4, 4, 4, 2]])