In [1]:
import numpy as np

In [2]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.eye(5,k=3) # köşeeni k birim öteledi

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.diag([1,2,4,31,5])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  4,  0,  0],
       [ 0,  0,  0, 31,  0],
       [ 0,  0,  0,  0,  5]])

In [16]:
r =np.random.randint(0,3,(5,5))
r

array([[2, 1, 2, 2, 0],
       [1, 0, 0, 0, 2],
       [2, 0, 1, 2, 2],
       [0, 2, 0, 1, 2],
       [0, 2, 2, 2, 0]])

In [ ]:
np.diag(r) # onceden olusturulmus matrıxın köşefenlerını gosterır

array([2, 0, 1, 1, 0])

In [18]:
np.diag(np.diag(r))

array([[2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])