In [3]:
import numpy as np

matris = np.random.randint(1,10,(5,5))

In [4]:
matris

array([[2, 7, 1, 2, 7],
       [7, 5, 3, 3, 8],
       [9, 6, 7, 9, 1],
       [8, 1, 7, 6, 4],
       [2, 5, 4, 7, 5]])

In [5]:
matris > 5

array([[False,  True, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True, False],
       [ True, False,  True,  True, False],
       [False, False, False,  True, False]])

In [6]:
matris[matris > 5]

array([7, 7, 7, 8, 9, 6, 7, 9, 8, 7, 6, 7])

In [7]:
matris[matris < 5]

array([2, 1, 2, 3, 3, 1, 1, 4, 2, 4])

In [8]:
matris[matris == 5]

array([5, 5, 5])

In [9]:
matris[matris == 7].size

6

In [10]:
matris % 2 == 0

array([[ True, False, False,  True, False],
       [False, False, False, False,  True],
       [False,  True, False, False, False],
       [ True, False, False,  True,  True],
       [ True, False,  True, False, False]])

In [11]:
matris[matris %2 == 0]

array([2, 2, 8, 6, 8, 6, 4, 2, 4])

In [12]:
sifir = matris == 0
cift = matris % 2 == 0


In [13]:
matris[cift]

array([2, 2, 8, 6, 8, 6, 4, 2, 4])

In [14]:
matris[sifir]

array([], dtype=int32)