In [5]:
import numpy as np

m1 = np.ones((5,5))
m2 = np.full((5,5),19)



In [2]:
m1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
m2

array([[19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19],
       [19, 19, 19, 19, 19]])

In [4]:
m1*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [5]:
m2+3

array([[22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22]])

In [6]:
m1 + m2

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [7]:
m2 - m1

array([[18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.],
       [18., 18., 18., 18., 18.]])

In [8]:
m2 / 3

array([[6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333],
       [6.33333333, 6.33333333, 6.33333333, 6.33333333, 6.33333333]])

In [9]:
m2 // 3

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int32)

In [10]:
m2 % 3


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [11]:
m3 = np.full((5,6),2)

In [12]:
m3

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [13]:
m3.shape

(5, 6)

In [14]:
m2.shape

(5, 5)

In [19]:
m3 = m3.reshape(30)[:25].reshape(5,5)


In [20]:
m2 + m3

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21]])

In [23]:
m1[0]=m1[0]*3

In [24]:
m1

array([[3., 3., 3., 3., 3.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
m4 = np.random.randint(0,4,(5,8))

In [7]:
m5 =np.arange(5).reshape(5,1)

In [8]:
m1 * m5

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [9]:
m1 /  m5 

C:\Users\mehmet\AppData\Local\Temp\ipykernel_26284\444987268.py:1: RuntimeWarning: divide by zero encountered in divide
  m1 /  m5


array([[       inf,        inf,        inf,        inf,        inf],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.5       , 0.5       , 0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.25      , 0.25      , 0.25      , 0.25      , 0.25      ]])

In [10]:
m6 = m1 + m5

In [11]:
m6 *np.diag(m6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  4.,  6.,  8., 10.],
       [ 3.,  6.,  9., 12., 15.],
       [ 4.,  8., 12., 16., 20.],
       [ 5., 10., 15., 20., 25.]])