In [1]:
import numpy as np
matris = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [2]:
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
matris[0]

array([1, 2, 3, 4])

In [5]:
matris[1]

array([5, 6, 7, 8])

In [ ]:
matris[2,0:1] #virgülün sol tarafı satrları ,sağ tarafı sutunları seçer

array([9])

In [16]:
matris[:,0]

array([ 1,  5,  9, 13])

In [18]:
matris[1:3,1:3]

array([[ 6,  7],
       [10, 11]])