In [1]:
import numpy as np

m1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [2]:
m1.shape


(3, 4)

In [3]:
m1.size

12

In [4]:
m1.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
m1.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [6]:
m1.reshape (12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
np.random.randint(0,2,(8,6)).reshape(6,8)

array([[1, 0, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 0, 1, 0]])

In [12]:
np.linspace(0,20,30).reshape(6,5)

array([[ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069],
       [ 3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655],
       [ 6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241],
       [10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828],
       [13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414],
       [17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ]])